version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - MYSQL_ROOT_PASSWORD=senha-admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=senha-user
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - /mnt/dados:/mnt/dados
    links:
      - mariadb
    environment:
      - MYSQL_PASSWORD=senha-user
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=senha-admin-nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=dominio.com
