version: '3'
services:
  yacht:
    image: selfhostedpro/yacht
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /home/pi/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock