version: '3'
services:
  transmission:
    image: linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /home/pi/transmission/config:/config
      - /home/pi/transmission/watch:/watch
      - /home/pi/transmission/downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always